### ISSUE TITLE
Problem running Auto-WEKA: Quote parse error.

### ISSUE THREAD

**Issue by PascalTurbo** [larskotthoff/autoweka#30] opened 2016-11-07 12:46 UTC
Hi There,

I've just installed Auto-WEKA using WEKA 3.8 and its Package Manager.
Then I've created my model using StringToWordVector and simply started Auto-WEKA.

But at the end of the Process, it fails with the error "Quote parse error."

**Comment by larskotthoff** [comment] 2016-11-07 17:30
Could you give me more detail on what you're doing and your setup please? It would also help if you could share the dataset -- everything I need to reproduce the bug. Thanks!

**Comment by PascalTurbo** [comment] 2016-11-08 08:49
OK, I've reinstalled WEKA and described the steps necessary to reproduce the problem:

Env:
- Windows 10
- WEKA 3.8 installed using installer
- Auto-WEKA installed using GUI Package Manager

Steps:
1. Open the auto-weka.arff [auto-weka.zip](https://github.com/automl/autoweka/files/577696/auto-weka.zip)
2. Select "Auto-WEKA" Tab
3. Select Attribute "(Nom) @@class@@)"
4. Set timeLimit to 2 or 3min
5. Press Start and Wait

Maybe you need to execute "Start" multiple times. On my last test it works - all following tests are failing.

I've also found more log information this time - and the error changes:

```
2016-11-08 09:09:54.572 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:09:54.571 [main] WARN Experiment - [WARN ] Algorithm Run Result reported a runtime of 23.218748092651367 (secs) that exceeded it's cutoff time of 15.0 (secs) by 8.218748092651367 (secs). Next warning at 9.218748092651367 (secs)  
2016-11-08 09:10:05.468 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.468 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  2016-11-08 09:10:05.458 [main] ERROR Wrapper - Failed to instantiate 'weka.classifiers.functions.GaussianProcesses' with options [-L, 0.19272995487314457, -N, 2, -K, weka.classifiers.functions.supportVector.RBFKernel -C 0.01571199579209244]: For input string: "0.01571199579209244"
2016-11-08 09:10:05.472 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.468 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  java.lang.RuntimeException: Failed to instantiate 'weka.classifiers.functions.GaussianProcesses' with options [-L, 0.19272995487314457, -N, 2, -K, weka.classifiers.functions.supportVector.RBFKernel -C 0.01571199579209244]: For input string: "0.01571199579209244"
2016-11-08 09:10:05.474 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.468 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at autoweka.ClassifierRunner._run(ClassifierRunner.java:257)
2016-11-08 09:10:05.476 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.468 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at autoweka.ClassifierRunner.access$000(ClassifierRunner.java:35)
2016-11-08 09:10:05.478 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at autoweka.ClassifierRunner$RunnerThread.doWork(ClassifierRunner.java:90)
2016-11-08 09:10:05.481 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at autoweka.WorkerThread.run(WorkerThread.java:26)
2016-11-08 09:10:05.483 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]  Caused by: java.lang.NumberFormatException: For input string: "0.01571199579209244"
2016-11-08 09:10:05.484 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at java.lang.NumberFormatException.forInputString(Unknown Source)
2016-11-08 09:10:05.486 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at java.lang.Integer.parseInt(Unknown Source)
2016-11-08 09:10:05.488 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at java.lang.Integer.parseInt(Unknown Source)
2016-11-08 09:10:05.490 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.classifiers.functions.supportVector.CachedKernel.setOptions(CachedKernel.java:128)
2016-11-08 09:10:05.491 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.classifiers.functions.supportVector.RBFKernel.setOptions(RBFKernel.java:191)
2016-11-08 09:10:05.492 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.469 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.core.Utils.forName(Utils.java:1096)
2016-11-08 09:10:05.494 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.470 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.classifiers.functions.supportVector.Kernel.forName(Kernel.java:364)
2016-11-08 09:10:05.495 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.470 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.classifiers.functions.GaussianProcesses.setOptions(GaussianProcesses.java:692)
2016-11-08 09:10:05.496 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.470 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.core.Utils.forName(Utils.java:1096)
2016-11-08 09:10:05.497 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.471 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
2016-11-08 09:10:05.499 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.471 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    at autoweka.ClassifierRunner._run(ClassifierRunner.java:248)
2016-11-08 09:10:05.500 [Thread-21] WARN AutoWEKAClassifier - 2016-11-08 09:10:05.471 [main] WARN Experiment - [WARN ] [PROCESS-ERR]    ... 3 more
2016-11-08 09:10:52.859 [Thread-21] INFO AutoWEKAClassifier - Estimated mean quality of final incumbent config 7 (internal ID: 0x162F7) on test set: 100.0, based on 1 run(s) on 1 test instance(s).
2016-11-08 09:10:55.083 [Thread-20] INFO TrajectoryMerger - Experiment C:\Users\username\AppData\Local\Temp\autoweka333155233448319298\Auto-WEKA
2016-11-08 09:10:55.147 [Thread-20] INFO AutoWEKAClassifier - classifier: weka.classifiers.trees.RandomForest, arguments: [-I, 16, -K, 0, -depth, 0], attribute search: null, attribute search arguments: [], attribute evaluation: null, attribute evaluation arguments: []
2016-11-08 09:18:16.051 [Thread-24] WARN AutoWEKAClassifier - 2016-11-08 09:18:16.051 [main] WARN Experiment - [WARN ] Algorithm Run Result reported a runtime of 113.828125 (secs) that exceeded it's cutoff time of 75.0 (secs) by 38.828125 (secs). Next warning at 39.828125 (secs)  
2016-11-08 09:18:16.053 [Thread-24] WARN AutoWEKAClassifier - 2016-11-08 09:18:16.051 [main] WARN Experiment - [WARN ] Algorithm Run Result reported wallclock time of 113.159 (secs) that exceeded it's cutoff time of 75.0 (secs) by 38.159000000000006 (secs). Next warning at 39.159000000000006 (secs)  
2016-11-08 09:18:28.874 [Thread-24] WARN AutoWEKAClassifier - 2016-11-08 09:18:28.874 [main] WARN Experiment - [WARN ] [PROCESS-ERR] 2016-11-08 09:18:28.844 [main] ERROR Wrapper - Failed to instantiate 'weka.classifiers.functions.GaussianProcesses' with options [-L, 0.19272995487314457, -N, 2, -K, weka.classifiers.functions.supportVector.RBFKernel -C 0.01571199579209244]: For input string: "0.01571199579209244"
2016-11-08 09:24:43.538 [Thread-24] INFO AutoWEKAClassifier - Estimated mean quality of final incumbent config 4 (internal ID: 0xC042) on test set: 100.0, based on 1 run(s) on 1 test instance(s).
2016-11-08 09:24:49.365 [Thread-23] INFO TrajectoryMerger - Experiment C:\Users\username\AppData\Local\Temp\autoweka3017551617947306975\Auto-WEKA
2016-11-08 09:24:49.397 [Thread-23] INFO AutoWEKAClassifier - classifier: weka.classifiers.meta.Vote, arguments: [-R, MAX, -S, 1, -B, weka.classifiers.lazy.KStar -B 52 -M d, -B, weka.classifiers.rules.M5Rules -N -M 1 -U, -B, weka.classifiers.rules.ZeroR, -B, weka.classifiers.trees.RandomForest -I 11 -K 1 -depth 0, -B, weka.classifiers.functions.SMOreg -C 0.5669325054023362 -N 2 -I "weka.classifiers.functions.supportVector.RegSMOImproved"-K "weka.classifiers.functions.supportVector.Puk -S 6.813083835746526 -O 0.4241406212916966""], attribute search: weka.attributeSelection.GreedyStepwise, attribute search arguments: [-C, -N, 315], attribute evaluation: weka.attributeSelection.CfsSubsetEval, attribute evaluation arguments: [-L]
java.lang.Exception: Quote parse error.
    weka.core.Utils.splitOptions(Utils.java:976)
    weka.classifiers.MultipleClassifiersCombiner.setOptions(MultipleClassifiersCombiner.java:98)
    weka.classifiers.RandomizableMultipleClassifiersCombiner.setOptions(RandomizableMultipleClassifiersCombiner.java:91)
    weka.classifiers.meta.Vote.setOptions(Vote.java:378)
    weka.core.Utils.forName(Utils.java:1096)
    weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
    weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:390)
    weka.gui.explorer.AutoWEKAPanel$11.run(AutoWEKAPanel.java:411)

    at weka.core.Utils.splitOptions(Utils.java:976)
    at weka.classifiers.MultipleClassifiersCombiner.setOptions(MultipleClassifiersCombiner.java:98)
    at weka.classifiers.RandomizableMultipleClassifiersCombiner.setOptions(RandomizableMultipleClassifiersCombiner.java:91)
    at weka.classifiers.meta.Vote.setOptions(Vote.java:378)
    at weka.core.Utils.forName(Utils.java:1096)
    at weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
    at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:390)
    at weka.gui.explorer.AutoWEKAPanel$11.run(AutoWEKAPanel.java:411)
2016-11-08 09:42:57.537 [Thread-27] WARN AutoWEKAClassifier - 2016-11-08 09:42:57.536 [main] WARN Experiment - [WARN ] Algorithm Run Result reported a runtime of 15.40625 (secs) that exceeded it's cutoff time of 10.0 (secs) by 5.40625 (secs). Next warning at 6.40625 (secs)  
2016-11-08 09:43:33.716 [Thread-27] INFO AutoWEKAClassifier - Estimated mean quality of final incumbent config 4 (internal ID: 0xC042) on test set: 1.0E100, based on 1 run(s) on 1 test instance(s).
2016-11-08 09:43:38.388 [Thread-26] INFO TrajectoryMerger - Experiment C:\Users\username\AppData\Local\Temp\autoweka2105989234147027938\Auto-WEKA
2016-11-08 09:43:38.472 [Thread-26] INFO AutoWEKAClassifier - classifier: null, arguments: [], attribute search: null, attribute search arguments: [], attribute evaluation: null, attribute evaluation arguments: []
java.lang.NullPointerException
    java.lang.String.contains(Unknown Source)
    weka.core.ClassCache.find(ClassCache.java:399)
    weka.core.ClassDiscovery.find(ClassDiscovery.java:310)
    weka.Run.findSchemeMatch(Run.java:81)
    weka.core.Utils.forName(Utils.java:1070)
    weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
    weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:390)
    weka.gui.explorer.AutoWEKAPanel$11.run(AutoWEKAPanel.java:411)

    at java.lang.String.contains(Unknown Source)
    at weka.core.ClassCache.find(ClassCache.java:399)
    at weka.core.ClassDiscovery.find(ClassDiscovery.java:310)
    at weka.Run.findSchemeMatch(Run.java:81)
    at weka.core.Utils.forName(Utils.java:1070)
    at weka.classifiers.AbstractClassifier.forName(AbstractClassifier.java:91)
    at weka.classifiers.meta.AutoWEKAClassifier.buildClassifier(AutoWEKAClassifier.java:390)
    at weka.gui.explorer.AutoWEKAPanel$11.run(AutoWEKAPanel.java:411)

```

**Comment by larskotthoff** [comment] 2016-11-08 23:17
Thanks for the additional information. I still can't reproduce the problem though -- what seed are you using? I've put a debug build of the latest development version at http://www.cs.ubc.ca/~larsko/autoweka.zip. Could you install this through the WEKA package manager please (putting the URL in there directly should work) and give it a try?

**Comment by larskotthoff** [comment] 2017-01-26 17:33
Closing as I can't reproduce this. Please reopen if you can provide more information.

**Closed as completed by larskotthoff** 2017-01-26 17:33 UTC
