### ISSUE TITLE
Autoweka 2.5 threads wont kill on Stop - Weka explorer 3.8

### ISSUE THREAD

**Issue by nikoskr** [larskotthoff/autoweka#45] opened 2017-05-05 15:05 UTC
Please add it in your to-do list.

**Comment by larskotthoff** [comment] 2017-05-05 15:14
Can you please describe in more detail what the issue is? No new classifier evaluations should be started after you click stop, but the current one may take a second or so to complete.

**Comment by nikoskr** [comment] 2017-05-06 11:46
Autoweka  config is almost the default apart from -parallelRuns 2
weka.classifiers.meta.AutoWEKAClassifier -seed 123 -timeLimit 15 -memLimit 1024 -nBestConfigs 1 -metric errorRate -parallelRuns 2.
Threads started to execute models for a while (i.e. 2 minutes) and then I press the Stop button in the Weka Explorer. The "weka" bird stops moving, yet threads are still working ( i.e. as it shows on the status bar and on task manager). This continues till the end of the timelimit of the predefined job

**Comment by larskotthoff** [comment] 2017-05-07 17:02
Ok, thanks. Does this happen with just a single run as well?

**Comment by nikoskr** [comment] 2017-05-07 18:05
This is true. It occurs with single runs

**Comment by larskotthoff** [comment] 2017-07-05 17:09
Thanks for your patience and sorry for the delay. I've just pushed a fix for this, which will be in the next release. I'm closing this issue; please check and if it persists, reopen.

**Closed as completed by larskotthoff** 2017-07-05 17:09 UTC
