### ISSUE TITLE
IllegalAccessError on "Save model" from Auto-WEKA panel

### ISSUE THREAD

**Issue by mrendleman** [larskotthoff/autoweka#49] opened 2017-06-20 16:32 UTC
After running Auto-WEKA from the Auto-WEKA panel, right clicking the run in the result list and clicking "Save model" yields the following error:

Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: tried to access method weka.gui.explorer.ClassifierPanel.saveClassifier(Ljava/lang/String;Lweka/classifiers/Classifier;Lweka/core/Instances;)V from class weka.gui.explorer.AutoWEKAPanel$12

As expected, this error doesn't occur if the AutoWEKAClassifier is run from the Classify panel.

**Comment by larskotthoff** [comment] 2017-06-21 23:25
Thanks for the report, I'll have a look.

**Comment by larskotthoff** [comment] 2017-07-05 16:52
I've tried to reproduce this, but it always works for me. Can you give me some more information about your operating system, Java version, and how you're running this please?

**Comment by mrendleman** [comment] 2017-07-05 17:11
Certainly! I'm on OS X 10.11.6, running Weka 3.9.1, Java version 1.8.0_73.

As described in the manual, I start Weka from the command line, in /Applications/weka-3-9-1-oracle-jvm.app/Contents/Java with the command "java -jar weka.jar". Then, in the auto-weka tab, I run auto-weka. After it's done, I right-click the run in the result list, and click "Save model". It doesn't bring up the dialog box like it does in the Classify tab, and the log gives me the IllegalAccessError (the entire log starting with the error: pastebin.com/YXHhSVPk )

**Comment by larskotthoff** [comment] 2017-07-05 19:51
Hmm, there were some weird things about Java on Mac OS. How did you install it?

**Comment by larskotthoff** [comment] 2017-07-07 21:10
Ok, so it seems that this error is caused by the classes being in different class loaders. Do you have 2 JDKs installed by chance? E.g. the system one and then installed WEKA with a JDK?

**Comment by larskotthoff** [comment] 2017-07-11 16:38
As far as I can tell, this doesn't have anything to do with Auto-WEKA, but is caused by the specific system configuration. I'm closing here, but please feel free to reopen if there's something concrete that can be done in Auto-WEKA to address this.

**Closed as completed by larskotthoff** 2017-07-11 16:38 UTC
