### ISSUE TITLE
Could not find SMAC executable

### ISSUE THREAD

**Issue by DavideRossi** [larskotthoff/autoweka#16] opened 2016-03-03 14:31 UTC
I'm getting this error whenever I push the "Start" button.
My guess is that this is a problem with Windows systems when a space is in the smac.bat path. In my case the full path is "c:\Users\Davide Rossi\wekafiles\packages\Auto-WEKA\smac-v2.10.03-master-778\smac.bat" that is reported as "c:\Users\Davide%20Rossi\wekafiles\packages\Auto-WEKA\smac-v2.10.03-master-778\smac.bat" in the error message.

**Comment by larskotthoff** [comment] 2016-03-03 17:16
Thanks for the report. I'll have a look at this ASAP.

**Comment by larskotthoff** [comment] 2016-03-03 20:22
This should be fixed now -- could you try http://www.cs.ubc.ca/~larsko/autoweka.zip (install this as a package through the package manager) please and let me know if it works for you?

**Comment by larskotthoff** [comment] 2016-03-04 22:18
I've tested on Windows and Linux and both work fine for me, so I'm closing this. Please reopen if you're still having problems.

**Closed as completed by larskotthoff** 2016-03-04 22:18 UTC

**Comment by PabloITPhD** [comment] 2016-10-26 17:10
I'm having the same issue but my guess is this time is caused by the accent mark on my username. My path is "C:\Users\Pablo Córdova\ ....\smac.bat" but is reported as "C:\Users\Pablo CȻrdova\ ....\smac.bat"

**Comment by larskotthoff** [comment] 2016-10-26 18:03
This looks like a character encoding issue. What encoding is your Windows installation using? You can set `-Dfile.encoding=...` when starting WEKA from the commandline.

**Comment by krisztiankarolyi** [comment] 2023-11-27 09:39
Hello, I have the same issue with the character encoding. How do I start the program via cmd with encdofing parameters?
Thanks
